services:
    huh.categories.listener.hooks:
        class: HeimrichHannot\CategoriesBundle\EventListener\HookListener
        arguments:
            - "@contao.framework"
            - '@huh.request'