services:
    huh.categories.manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryManager
        arguments:
            - "@contao.framework"
    huh.categories.config_manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryConfigManager
        arguments:
            - "@contao.framework"
    huh.categories.context_manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryContextManager
        arguments:
            - "@contao.framework"
    huh.categories.property_cache_manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryPropertyCacheManager
        arguments:
            - "@contao.framework"
    huh.categories.picker.category_provider:
        class: HeimrichHannot\CategoriesBundle\Picker\CategoryPickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 512 }