services:
    huh.categories.manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryManager
        public: true
        arguments:
            - "@contao.framework"
    huh.categories.config_manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryConfigManager
        public: true
        arguments:
            - "@contao.framework"
    huh.categories.context_manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryContextManager
        public: true
        arguments:
            - "@contao.framework"
    huh.categories.property_cache_manager:
        class: HeimrichHannot\CategoriesBundle\Manager\CategoryPropertyCacheManager
        public: true
        arguments:
            - "@contao.framework"
    huh.categories.picker.category_provider:
        class: HeimrichHannot\CategoriesBundle\Picker\CategoryPickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 512 }
    huh.categories.twig_extension:
        class: HeimrichHannot\CategoriesBundle\Twig\CategoryExtension
        public: false
        tags:
            - {name: twig.extension}

# Filter

    huh.categories.filter.choice:
        class: HeimrichHannot\CategoriesBundle\Filter\Choice\CategoriesChoice
        public: true
        arguments:
          - "@contao.framework"
          - '@huh.categories.manager'